version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: catalog-service
    ports:
      - "27020:27017"
    volumes:
      - ./data:/data/db # Alterado para usar o diretório 'data' no host
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-catalog
    ports:
      - "8020:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: always
